### ISSUE TITLE
Shep Code Review

### ISSUE THREAD

**Issue by foodforcode** [klarbars/hollinster#50]
Hi team!
Great work getting through your FEC!

Your FEC Team worked hard and built an impressive product. As a part of your web-development portfolio of projects, your FEC repository should be something you are excited to share with other engineers. Spend some additional time working to make it a valuable asset to your portfolio for use during your job search.

Please take a look at the following:

General observations:

- Amazing consistent use of functional components and hooks
- Do a sweep to remove extraneous and unused imports
- Keep code clean; delete unnecessary files or comments and old code that has been refactored
- Error handling
- Take some time to set up a presentable readme! This is likely what employers will look at over everything else
- Remove any console.logs for production
- Name files and variables appropriately. Things may have changed significantly from the time you first defined them
- Ensure code is not difficult to read, use a new line for each element property if it is getting too long

**Comment by johnamielyasis** [comment]
Thanks for the feedback Connie!
