### ISSUE TITLE
should default style for Large be an array?

### ISSUE THREAD

**Issue by phil-ho** [klarbars/hollinster#7]
https://github.com/klarbars/hollinster/blob/4f29cf2002f4273be309ddc0046e56d29aace102/client/src/components/overview/ImgGallery/Gallery.jsx#L19-L21

@claire123c 

I'm not sure if your `Large` component needs to use an array for the `defaultStyle` prop. From the looks of the code, it only ever uses the first element in the array.  If that is the case, consider using  [Array.prototype.find](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find) to pull a single element out of an array. Also, your variable naming of `defaultStyle` suggests you are passing a single object, vs `defaultStyles` which would indicate an array.

PS - I think the BRD states that there can be a default style but if none exists, then to take the first in the array? (I might be wrong on this) If I'm right, you might want to handle the case where no `default === true` case exists

**Comment by claire123c** [comment]
Thanks for the feedback Phil!
